### ISSUE TITLE
How do you use Cerberus

### ISSUE THREAD

**Issue by Mobmaker55** [elysium-suite/cerberus#10]
There's no documentation, I simply don't understand how to use this program.

**Comment by safinsingh** [comment]
Cerberus is still a work in progress. Documentation will be added once it's finished.

**Comment by Mobmaker55** [comment]
That's cool and all, but how do I use it xD

what is this "file server" or whatever I'm supposed to be connecting to?
I can probably figure it out from there...

**Comment by safinsingh** [comment]
You can host the file server in question using [orthrus](https://github.com/elysium-suite/orthrus.rs).

**Comment by Akshay-Rohatgi** [comment]
Cerberus is not finished, it is not meant to be used yet.

**Comment by aaditgupta21** [comment]
It is basically supposed to be an easier way to set up an image with aeacus

**Comment by Mobmaker55** [comment]
just askin then, if we weren't supposed to use it, why is it recommended to be used for aeacus??
it's the second line in the aeacus readme...

**Comment by safinsingh** [comment]
Sorry, we'll make it more clear that it's not ready for stable use yet. Feel free to look through the source code to get a better idea of what it does :)
